/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.mooncell.panel.xml -i qpaneldbus.h -c QPanelAdaptor -a qpaneladaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QPANELADAPTOR_H_1419582215
#define QPANELADAPTOR_H_1419582215

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "qpaneldbus.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.mooncell.panel.interface
 */
class QPanelAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.mooncell.panel.interface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.mooncell.panel.interface\">\n"
"    <method name=\"setLed\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"on1off0\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"setBz\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"on1off0\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"hz\"/>\n"
"    </method>\n"
"    <method name=\"setLcd\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"setLcdLine\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"setLcdClear\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setLcdClearLine\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"y\"/>\n"
"    </method>\n"
"    <method name=\"setLcdFull\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"setLcdFullLine\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"setLcdPos\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"on1off0\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"pos\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QPanelAdaptor(QObject *parent);
    virtual ~QPanelAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool setBz(uchar on1off0, uchar hz);
    bool setLcd(uchar x, uchar y, const QByteArray &data);
    bool setLcdClear();
    bool setLcdClearLine(uchar y);
    bool setLcdFull(uchar data);
    bool setLcdFullLine(uchar y, uchar data);
    bool setLcdLine(uchar y, const QByteArray &data);
    bool setLcdPos(uchar on1off0, uchar pos);
    bool setLed(uchar on1off0, uchar index);
Q_SIGNALS: // SIGNALS
};

#endif
